# Generated by Django 3.2.3 on 2021-05-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='val',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='pics')),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField()),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
